### ISSUE TITLE
AWS opsworks - 11.10 - berkshelf 3.2.0 error when it gets to et_fog

### ISSUE THREAD

**Issue by Arametheus** [evertrue/et_nat-cookbook#3]
I keep getting this error in the current version. any help would be great since this script looks like what i would need.

I tried both Linux and ubuntu

NoMethodError
-------------
undefined method `compile_time' for Chef::Resource::ChefGem
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/et_fog/recipes/default.rb:30:in `block in from_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/et_fog/recipes/default.rb:29:in `from_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/et_nat/recipes/default.rb:10:in `from_file'
 
 
Relevant File Content:
----------------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/et_fog/recipes/default.rb:
 
23:  # Dependencies required by nokogiri (for fog)
24:  node['et_fog']['dependencies'].each do |pkg|
25:    c_pkg = package(pkg)
26:    c_pkg.run_action(:install)
27:  end
28:  
29:  chef_gem 'unf' do
30>>   compile_time true
31:  end
32:  
33:  # TODO: Remove this once the gem_hell cookbook is ready to roll
34:  
35:  chef_gem 'fog' do
36:    compile_time true
37:    version node['et_fog']['version']
38:  end
39:

**Comment by jeffbyrnes** [comment]
@Arametheus this is due to the fact that the `compile_time` property of the `chef_gem` resource is only available in Chef >= 12.1.0. Apologies that the cookbook doesn’t specify that it requires at least that version of Chef or greater.

Thankfully, you can use Chef 12 w/ OpsWorks. Please see AWS’ [blog post on Chef 12 for OpsWorks](https://blogs.aws.amazon.com/application-management/post/Tx1T5HNA1TSU8NH/AWS-OpsWorks-Now-Supports-Chef-12-for-Linux) for details.

That said, I can tweak this to be backwards compatible, and so I shall.

**Comment by jeffbyrnes** [comment]
Though, to be more accurate, this is a bug with [et_fog](https://github.com/evertrue.com/et_fog-cookbook), so I’ll close this.

**Comment by jeffbyrnes** [comment]
@Arametheus you should be all good now, thanks to et_fog v1.3.2.

**Comment by Arametheus** [comment]
awesome thank you
